# -*- coding: utf-8 -*-
"""Downloading_Tar_file_from_IBM (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkhxQySyuVv8YXtJC8B7U6Ny6mH4e2Nx
"""

!pip install watson-machine-learning-client --upgrade

!pip install ibm_watson_machine_learning

from ibm_watson_machine_learning import APIClient
wml_credentials={"url":"https://us-south.ml.cloud.ibm.com",
                "apikey":"1yjPVMW5T1-4ID-jKcs9o1waDEhzbkc7dSP-6PcJor0b"}
client = APIClient(wml_credentials)

client = APIClient(wml_credentials)

client

space_uid="60f59b49-8b36-4a7f-9284-b6daed152631"

client.set.default_space(space_uid)



model_id = '50250da9-1bde-4614-8250-2f41a959e352'

client.repository.download(model_id,'model.tar.gb')

